"""office -> city, psc,street, house_number

Revision ID: 5d69dc3ead9f
Revises: 8d90cfebc291
Create Date: 2026-05-15 23:42:15.226834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d69dc3ead9f'
down_revision: Union[str, Sequence[str], None] = '8d90cfebc291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('city', sa.String(), nullable=False))
    op.add_column('clients', sa.Column('psc', sa.String(), nullable=False))
    op.add_column('clients', sa.Column('street', sa.String(), nullable=False))
    op.add_column('clients', sa.Column('house_number', sa.String(), nullable=False))
    op.drop_column('clients', 'office')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('office', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('clients', 'house_number')
    op.drop_column('clients', 'street')
    op.drop_column('clients', 'psc')
    op.drop_column('clients', 'city')
    # ### end Alembic commands ###
