"""add table_args in Tag

Revision ID: 64c9e4bc3e94
Revises: 6fe660f7e5fe
Create Date: 2026-06-11 23:05:47.344599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64c9e4bc3e94'
down_revision: Union[str, Sequence[str], None] = '6fe660f7e5fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_tag_name_owner', 'tags', ['name', 'owner_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tag_name_owner', 'tags', type_='unique')
    # ### end Alembic commands ###
