"""empty message

Revision ID: 6c4e79e9efd7
Revises: 781585e36c1d
Create Date: 2026-05-18 04:21:12.039211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c4e79e9efd7'
down_revision: Union[str, Sequence[str], None] = '781585e36c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.String(), nullable=False))
    op.add_column('users', sa.Column('psc', sa.String(), nullable=False))
    op.add_column('users', sa.Column('street', sa.String(), nullable=True))
    op.add_column('users', sa.Column('house_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'house_number')
    op.drop_column('users', 'street')
    op.drop_column('users', 'psc')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###
