"""street and house_number are default value

Revision ID: 6fda9e49a38d
Revises: 35822a286a25
Create Date: 2026-05-16 01:57:40.846991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fda9e49a38d'
down_revision: Union[str, Sequence[str], None] = '35822a286a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'street',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clients', 'house_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'house_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clients', 'street',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
