"""clients: dic are default, add phone number

Revision ID: 70e253c119f4
Revises: ce2cf0641f28
Create Date: 2026-05-14 18:20:37.276521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e253c119f4'
down_revision: Union[str, Sequence[str], None] = 'ce2cf0641f28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('phone_number', sa.String(), nullable=True))
    op.alter_column('clients', 'dic',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'dic',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('clients', 'phone_number')
    # ### end Alembic commands ###
