"""add total_amount into Invoice table

Revision ID: 7b80c84498fd
Revises: c78d29139bb9
Create Date: 2026-06-09 18:42:46.009695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b80c84498fd'
down_revision: Union[str, Sequence[str], None] = 'c78d29139bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'total_amount')
    # ### end Alembic commands ###
