"""rename table invoiceitems to invoice_items

Revision ID: 857ac5a0e638
Revises: b62d7e26afe7
Create Date: 2026-06-09 19:20:48.229763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '857ac5a0e638'
down_revision: Union[str, Sequence[str], None] = 'b62d7e26afe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("invoiceitems", "invoice_items")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("invoice_items","invoiceitems")
    # ### end Alembic commands ###
