"""Checker

Revision ID: 86b28ddb1e34
Revises: 885e77bfda93
Create Date: 2026-09-12 12:09:50.453851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86b28ddb1e34'
down_revision: Union[str, Sequence[str], None] = '885e77bfda93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log', 'changed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.alter_column('clients', 'vat',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_invoice_items_id'), 'invoice_items', ['id'], unique=False)
    op.add_column('invoice_tags', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('invoice_tags', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_invoice_tags_id'), 'invoice_tags', ['id'], unique=False)
    op.add_column('invoices', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.alter_column('refresh_tokens', 'revoked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.alter_column('refresh_tokens', 'revoked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('invoices', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('invoices', 'deleted_at')
    op.drop_index(op.f('ix_invoice_tags_id'), table_name='invoice_tags')
    op.alter_column('invoice_tags', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('invoice_tags', 'id')
    op.drop_index(op.f('ix_invoice_items_id'), table_name='invoice_items')
    op.alter_column('clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('clients', 'vat',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.alter_column('audit_log', 'changed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
