"""column street and house number is now not nullable

Revision ID: b19a119d54d4
Revises: 39e739729221
Create Date: 2026-06-28 14:23:40.609405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b19a119d54d4'
down_revision: Union[str, Sequence[str], None] = '39e739729221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'street',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'house_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'house_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'street',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
