"""add asociated table: invoice_tags

Revision ID: c78d29139bb9
Revises: e8d94323252d
Create Date: 2026-06-08 10:26:13.181609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c78d29139bb9'
down_revision: Union[str, Sequence[str], None] = 'e8d94323252d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_tags', sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_tags', 'added_at')
    # ### end Alembic commands ###
