"""clients: adress ->office, add column vat

Revision ID: ce2cf0641f28
Revises: f9cde8538faf
Create Date: 2026-05-14 15:44:34.227547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce2cf0641f28'
down_revision: Union[str, Sequence[str], None] = 'f9cde8538faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('office', sa.String(), nullable=False))
    op.add_column('clients', sa.Column('vat', sa.Boolean(), nullable=True))
    op.drop_column('clients', 'adress')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('adress', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('clients', 'vat')
    op.drop_column('clients', 'office')
    # ### end Alembic commands ###
